### ISSUE TITLE
Publish script

### ISSUE THREAD

**Issue by twisttaan** [Disploy/disploy#47]
Implement a script that publishes every package to NPM and overrides the version with the version in the root of the monorepo so all packages stay in sync version-wise.

This script can be ran by a GitHub action when the pacakage.json in the root of the monorepo is modified.

**Comment by twisttaan** [comment]
I’m not so sure about the keeping every package the same version.

**Comment by GodderE2D** [comment]
> I’m not so sure about the keeping every package the same version.

Yeah, each package should have its own version according to semver, and not using a main version.
