### ISSUE TITLE
Implement create-disploy-app with Go

### ISSUE THREAD

**Issue by twisttaan** [Disploy/disploy#50]
We should consider implementing the deploy cli in Go with the bubble tea library for a really good first impression for the user because of how professional and pretty bubble tea is.

**Comment by twisttaan** [comment]
This would simply download a tar ball of a “source code release” of disploy/starters (when it’s made) and ask the user which starter would they like to use which it gets from reading all the folders root of the repo. It would then copy everything from the folder into the new project and run yarn, pnpm or npm depending on what the user chose during the TUI wizard.

**Comment by GodderE2D** [comment]
Didn't you say something about integration with the framework so JS/TS was the best option?

**Comment by twisttaan** [comment]
> Didn't you say something about integration with the framework so JS/TS was the best option?

I merged the CLI and core package, it wouldn’t make sense to create boilerplate projects from the CLI anymore. create-disploy-app is seperate from the main `disploy` package.

**Comment by megatank58** [comment]
I'll happily work on this (do i need be formal here?) I've already done this sort of work in oxido

**Comment by twisttaan** [comment]
> I'll happily work on this (do i need be formal here?) I've already done this sort of work in oxido

Yes, you need to be formal here.

**Comment by twisttaan** [comment]
I've made the starters repo https://github.com/Disploy/starters

When installing the dependencies, instead of using `yarn`, `npm i`, `pnpm i`, etc use `yarn add disploy` since it's not included in the package.json.

**Comment by TogarashiPepper** [comment]
Perhaps instead of having a starters repo we could adopt a system to how create-vite works where the templates are stored within the package?

**Comment by twisttaan** [comment]
closed now that `create-disploy-app` is not in this repo https://github.com/Disploy/create-disploy-app
