### ISSUE TITLE
Missing tsc command in step 3 of README

### ISSUE THREAD

**Issue by GodderE2D** [Disploy/disploy#65]
README.md's Step 2 currently shows a TypeScript code snippet, and in order to run TypeScript code in Disploy, at least in development, you would [also need to run `tsc --watch` command alongside `disploy dev`](https://disploy.dev/docs/Guide/learning-the-workflow/dev-mode).

Occurrences:

- https://github.com/Disploy/disploy/blob/main/packages/disploy/README.md
- https://github.com/Disploy/disploy/blob/main/apps/docs/docs/Guide/getting-started/introduction.md

**Comment by twisttaan** [comment]
This shouldn't be an issue now since https://github.com/Disploy/disploy/pull/66
