### ISSUE TITLE
recommended node version incompatible with linux fs.watch

### ISSUE THREAD

**Issue by nyapat** [Disploy/disploy#85]
guide recommends node v18
node v14 added an error thrown when using fs.watch recursive on linux
node v19(.1) added the functionality for fs.watch recursive

https://github.com/Disploy/disploy/blob/5d9b4bf44eec441d297382b0c03ac0e51a113273/packages/disploy/cli/src/commands/dev.ts#L50
https://github.com/Disploy/disploy/blob/5d9b4bf44eec441d297382b0c03ac0e51a113273/packages/disploy/scripts/copyAssets.mjs#L30

**Comment by twisttaan** [comment]
Instead of updating to Node.js 19, I'm going to refactor all the `fs.watch` calls to use [chokidar](https://github.com/paulmillr/chokidar) instead.
